### PR TITLE
pscanrules: add alert refs to HashDisclosureScanRule

### LINKED ISSUE #9144: Hash Disclosure pscan rule raises multiple alerts with varying severity but same alertRef (10097)
### Describe the bug:

The [Hash Disclosure passive scan rule contains multiple patterns](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java#L62) to detect multiple types of hashes.

Each detection raises an alert with a distinct title, confidence _and severity_ but they all use the same alertRef. This means that the [official documentation for this alertRef](https://www.zaproxy.org/docs/alerts/10097/) may not match the alert title or severity observed in the scan results.

This is confusing, given that other plugins that produce multiple alerts with varying severity and title use a distinct alertRef for each, so they can be properly documented (e.g. 10097-1, 10097-2, etc.)

### Steps to reproduce the behavior:

Scan a website that contains multiple hash disclosures, and observe that all alerts have the same alertRef.

### Expected behavior:

Each distinct hash disclosure alert, unique by title and severity, should have a distinct alertRef identifier (e.g. 10097-1, 10097-2, etc.) so that they can be properly enumerated and [documented in the alert catalog](https://www.zaproxy.org/docs/alerts/).

### Software Versions:

All

### Screenshots:

_No response_

### Errors from the zap.log file:

_No response_

### Additional context:

_No response_

### Would you like to help fix this issue?

- [ ] Yes

### PR DESCRIPTION
**Pull request by maxullman**
## Overview
Added alert refs and example alerts for HashDisclosureScanRule plugin 10097 to disambiguate different hashes having different severities.

## Related Issues
Close https://github.com/zaproxy/zaproxy/issues/9144

### CODE REVIEW

**Comment by maxullman** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by maxullman** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [aefd221e\-1fe7\-485d\-8f03\-3e405ba318c1](https://eu.ast.checkmarx.net/projects/0da811fa-6373-42b1-bbb6-d0026285b136/scans?id=aefd221e-1fe7-485d-8f03-3e405ba318c1&branch=maxullman%2Falert-refs-10097)


---
<details><summary><b>New Issues (3)</b></summary>
Checkmarx found the following issues in this Pull Request

#|Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---|---
1|LOW|Unpinned Actions Full Length Commit SHA|/codeql\.yml: [35](https://github.com/maxullman/zap-extensions/blob/alert-refs-10097//.github/workflows/codeql.yml#L35)|<details><summary>details</summary>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release\. Pinning to a particular SHA help...</details>
2|LOW|Unpinned Actions Full Length Commit SHA|/codeql\.yml: [50](https://github.com/maxullman/zap-extensions/blob/alert-refs-10097//.github/workflows/codeql.yml#L50)|<details><summary>details</summary>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release\. Pinning to a particular SHA help...</details>
3|LOW|Unpinned Actions Full Length Commit SHA|/codeql\.yml: [31](https://github.com/maxullman/zap-extensions/blob/alert-refs-10097//.github/workflows/codeql.yml#L31)|<details><summary>details</summary>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release\. Pinning to a particular SHA help...</details>

</details>



---
Use @Checkmarx to interact with Checkmarx PR Assistant. 
*Examples:*
`@Checkmarx how are you able to help me?`
`@Checkmarx rescan this PR`

File: addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java [hunk 1]
```diff
@@ -61,32 +59,57 @@ public class HashDisclosureScanRule extends PluginPassiveScanner
...
+                new HashAlert(
+                        "SHA-256 Crypt",
+                        Alert.RISK_HIGH,
+                        Alert.CONFIDENCE_HIGH,
+                        5,
+                        "$5$MnfsQ4iN$ZMTppKN16y/tIsUYs/obHlhdP.Os80yXhTurpBMUbA5"));
         hashPatterns.put(
                 Pattern.compile("\\$5\\$rounds=[0-9]+\\$[./0-9A-Za-z]{0,16}\\$[./0-9A-Za-z]{43}"),
-                new HashAlert("SHA-256 Crypt", Alert.RISK_HIGH, Alert.CONFIDENCE_HIGH));
+                new HashAlert("SHA-256 Crypt", Alert.RISK_HIGH, Alert.CONFIDENCE_HIGH, 5, null));
```
Comment (thc202) [inline addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java]: Preferable to refactor the HashAlert to contain the patterns than rely on passing nulls.

Comment (maxullman) [reply addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java]: @thc202 thanks I refactored it to reuse those objects when there are multiple patterns, so there are no longer any null example evidences.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]
