### PR TITLE
reports: correct systemic state in JSON/XML reports

### LINKED ISSUE #9254: Discrepancy for "systemic" flag value in json and html reports if reported instances for an alert < systemic-limit value
### Describe the bug:

We found that when the number of reported instances for a systemic alert are less than systemic-limit, they are marked as "systemic: true" in json report, but not flagged as systemic in html report. We had set systemic-limit to default (5).

For example, we ran some scans and found that :

- Absence of Anti-CSRF Tokens - reported as 4 instances in the HTML report (not reported as systemic), but marked as "systemic: true" in the JSON report.
- Content Security Policy (CSP) Header Not Set - reported as 4 instances in the HTML report (not reported as systemic), but marked as "systemic: true" in the JSON report.
- Anti-CSRF Tokens Check - reported as 1 instances in the HTML report (not reported as systemic), but marked as "systemic: true" in the JSON report.

This causes discrepancy if a finding is marked as systemic in json report and and not marked as "systemic" in html report.

Please refer attached screenshot for html report findings.

Json report:

{
          "pluginid": "20012",
          "alertRef": "20012",
          "alert": "Anti-CSRF Tokens Check",
          "name": "Anti-CSRF Tokens Check",
          "riskcode": "2",
          "confidence": "2",
          "riskdesc": "Medium (Medium)",
          "desc": "<p>A cross-site request forgery is an attack that involves forcing a victim to send an HTTP request to a target destination without their knowledge or intent in order to perform an action as the victim. The underlying cause is application functionality using predictable URL/form actions in a repeatable way. The nature of the attack is that CSRF exploits the trust that a web site has for a user. By contrast, cross-site scripting (XSS) exploits the trust that a user has for a web site. Like XSS, CSRF attacks are not necessarily cross-site, but they can be. Cross-site request forgery is also known as CSRF, XSRF, one-click attack, session riding, confused deputy, and sea surf.</p><p></p><p>CSRF attacks are effective in a number of situations, including:</p><p>    * The victim has an active session on the target site.</p><p>    * The victim is authenticated via HTTP auth on the target site.</p><p>    * The victim is on the same local network as the target site.</p><p></p><p>CSRF has primarily been used to perform an action against a target site using the victim's privileges, but recent techniques have been discovered to disclose information by gaining access to the response. The risk of information disclosure is dramatically increased when the target site is vulnerable to XSS, because XSS can be used as a platform for CSRF, allowing the attack to operate within the bounds of the same-origin policy.</p>",
          "instances": [
            {
              "id": "112700",
              "uri": "http://<masked>/WebGoat/register.mvc",
              "nodeName": "http://<masked>/WebGoat/register.mvc ()(agree,matchingPassword,password,username)",
              "method": "POST",
              "param": "",
              "attack": "",
              "evidence": "<form class=\"form-horizontal\" action=\"/WebGoat/register.mvc\" method='POST'>",
              "otherinfo": ""
            }
          ],
          "count": "1",
          **"systemic": true,**
          "solution": "<p>Phase: Architecture and Design</p><p>Use a vetted library or framework that does not allow this weakness to occur or provides constructs that make this weakness easier to avoid.</p><p>For example, use anti-CSRF packages such as the OWASP CSRFGuard.</p><p></p><p>Phase: Implementation</p><p>Ensure that your application is free of cross-site scripting issues, because most CSRF defenses can be bypassed using attacker-controlled script.</p><p></p><p>Phase: Architecture and Design</p><p>Generate a unique nonce for each form, place the nonce into the form, and verify the nonce upon receipt of the form. Be sure that the nonce is not predictable (CWE-330).</p><p>Note that this can be bypassed using XSS.</p><p></p><p>Identify especially dangerous operations. When the user performs a dangerous operation, send a separate confirmation request to ensure that the user intended to perform that operation.</p><p>Note that this can be bypassed using XSS.</p><p></p><p>Use the ESAPI Session Management control.</p><p>This control includes a component for CSRF.</p><p></p><p>Do not use the GET method for any request that triggers a state change.</p><p></p><p>Phase: Implementation</p><p>Check the HTTP Referer header to see if the request originated from an expected page. This could break legitimate functionality, because users or proxies may have disabled sending the Referer for privacy reasons.</p>",
          "otherinfo": "",
          "reference": "<p>https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html</p><p>https://cwe.mitre.org/data/definitions/352.html</p>",
          "cweid": "352",
          "wascid": "9",
          "sourceid": "21139"
        },

### Steps to reproduce the behavior:

Run the scans and generate the json and html reports with the following templates:

Html - "Traditional html report"
Json report - "Traditional json report" Or "Traditional json report with requests and responses"

### Expected behavior:

- If the alert instances < systemic-limit, it may not be systemic. In that case, it should not be reported as systemic in json report.
- If the alert has property "systemic" : "true" in json report, it should reported as systemic in html report as well. Both should be consistent.

### Software Versions:

- ZAP 2.17.0
- Add-ons have been updated to the latest versions

### Screenshots:

[TraditionalHtmlReportSystemicProperty.pdf](https://github.com/user-attachments/files/25408983/TraditionalHtmlReportSystemicProperty.pdf)

### Errors from the zap.log file:

_No response_

### Additional context:

_No response_

### Would you like to help fix this issue?

- [ ] Yes

### PR DESCRIPTION
**Pull request by miguel-baptista07**
Fixes zaproxy/zaproxy#9254

## Root Cause
Alert.isSystemic() checks if the scan rule has the SYSTEMIC tag — a rule-level 
property set by scan rule authors. AlertNode.isSystemic() checks if the instance 
count >= systemic-limit — the correct check for reports.

The JSON and XML templates were calling helper.isSystemic(alert) with an Alert 
object, producing systemic=true whenever a rule had the SYSTEMIC tag, regardless 
of instance count. The HTML report was already correct because it operates on 
AlertNode objects directly.

## Changes
- Added ReportHelper.isSystemic(AlertNode, String, int) that locates the matching 
  AlertNode in the alert tree and delegates to AlertNode.isSystemic()
- Deprecated old isSystemic(Alert) overload
- Updated 4 templates: traditional-json, traditional-json-plus, traditional-xml, 
  traditional-xml-plus
- Added regression tests for JSON and XML reports
- Updated CHANGELOG.md

### CODE REVIEW

**Comment by miguel-baptista07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [e88b20ab\-f1a3\-4d3a\-8bde\-49b691090fba](https://eu.ast.checkmarx.net/projects/0da811fa-6373-42b1-bbb6-d0026285b136/scans?id=e88b20ab-f1a3-4d3a-8bde-49b691090fba&branch=miguel-baptista07%2Ffix%2Fsystemic-flag-discrepancy-9254)


---
<details><summary><b>New Issues (1)</b></summary>
Checkmarx found the following issues in this Pull Request

#|Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---|---
1|HIGH|[Improper_Restriction_of_Stored_XXE_Ref](https://eu.ast.checkmarx.net/results/0da811fa-6373-42b1-bbb6-d0026285b136/e88b20ab-f1a3-4d3a-8bde-49b691090fba/sast/description/611/6785932912615860392)|addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils\.java: [282](https://github.com/miguel-baptista07/zap-extensions/blob/fix/systemic-flag-discrepancy-9254/addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils.java#L282)|<details><summary>details</summary>The  loads and parses XML using parse, at line 511 of /addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsXmlUnitTest\.java\.  ...</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e88b20ab-f1a3-4d3a-8bde-49b691090fba/0da811fa-6373-42b1-bbb6-d0026285b136/sast?result-id=NtpzB5%2Fg6mO8zPx4P3sdFcz4ScI%3D&redirect=true)

</details>



---
Use @Checkmarx to interact with Checkmarx PR Assistant. 
*Examples:*
`@Checkmarx how are you able to help me?`
`@Checkmarx rescan this PR`

**Comment by thc202** [comment]
The commit author does not match the GitHub account.

File: addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java [hunk 1]
```diff
@@ -328,14 +328,42 @@ public static boolean isSystemic(AlertNode node) {
...
     /**
-     * Returns whether the alert node is systemic.
+     * Returns whether the alert has the systemic tag.
      *
      * @since 0.42.0
+     * @deprecated Use {@link #isSystemic(AlertNode, String, int)} instead, which determines
+     *     systemic status from the instance count in the alert tree, consistent with the HTML
+     *     report.
      */
+    @Deprecated(since = "0.45.0")
```
Comment (thc202) [inline addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java]: It would be better to fix the method to match the expected/wanted behaviour, instead of rewording/deprecating and introducing another one.

File: addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java [hunk 2]
```diff
@@ -328,14 +328,42 @@ public static boolean isSystemic(AlertNode node) {
...
             return false;
         }
         return alert.isSystemic();
     }
+
+    /**
+     * Returns whether the alert is systemic, based on the instance count in the alert tree.
+     *
+     * <p>This method finds the alert node matching the given name and risk in the root node and
+     * delegates to {@link #isSystemic(AlertNode)}, ensuring consistent behaviour with the HTML
```
Comment (thc202) [inline addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java]: It's not delegating (guess a hallucination), either update the docs or the implementation.
The call out of the HTML does not make sense since other reports than HTML worked like that (e.g. PDF, markdown) and all will behave the same thereafter.

File: addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java [hunk 3]
```diff
@@ -328,14 +328,42 @@ public static boolean isSystemic(AlertNode node) {
...
+     */
+    public static boolean isSystemic(AlertNode rootNode, String alertName, int alertRisk) {
+        if (rootNode == null) {
+            return false;
+        }
+        for (int i = 0; i < rootNode.getChildCount(); i++) {
+            AlertNode alertNode = rootNode.getChildAt(i);
+            if (alertNode.getChildAt(0) != null
+                    && alertNode.getRisk() == alertRisk
+                    && alertNode.getChildAt(0).getUserObject().getName().equals(alertName)) {
```
Comment (thc202) [inline addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java:350]: This should not be duplicated.

File: addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsJsonUnitTest.java [hunk 4]
```diff
@@ -758,4 +758,23 @@ void shouldGenerateValidJsonPlusReport() throws Exception {
         assertThat(tags.getJSONObject(0).getString("tag"), is(equalTo("tagkey")));
         assertThat(tags.getJSONObject(0).getString("link"), is(equalTo("tagvalue")));
     }
+
+    @Test
+    void shouldNotMarkSystemicWhenInstancesBelowThresholdEvenWithSystemicTag() throws Exception {
+        // Given - alert has SYSTEMIC tag but only 2 instances (below the systemic-limit of 5)
```
Comment (thc202) [inline addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsJsonUnitTest.java]: There's no given with that comment here, that's being done in the when…

File: addOns/reports/CHANGELOG.md [hunk 5]
```diff
@@ -4,6 +4,10 @@ All notable changes to this add-on will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 ## Unreleased
+### Fixed
+- Systemic flag in JSON and XML reports now correctly reflects instance count against the
+  systemic-limit, consistent with the HTML report (issue #9254).
```
Comment (thc202) [inline addOns/reports/CHANGELOG.md]:
```suggestion
- The alert's systemic flag in JSON and XML reports now correctly reflects its state (Issue 9254).
```

**Comment by miguel-baptista07** [comment]
All review comments addressed. Please let me know if anything else needs changing.

**Comment by miguel-baptista07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thc202** [comment]
The committer is still not the expected.

**Comment by miguel-baptista07** [comment]
Sorry about that, I was using the wrong email in my Git config. I've updated it to the one associated with my GitHub account and force-pushed. The committer should now show correctly.

**Comment by miguel-baptista07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kingthorin** [comment]
What's with the JavaDoc removals in `ReportHelper.java`?

**Comment by miguel-baptista07** [comment]
Sorry about that, those removals were unintentional. I'll restore the original Javadocs and push again.

**Comment by miguel-baptista07** [comment]
Javadocs restored, sorry about that. You can see them back in the latest commit.

**Comment by miguel-baptista07** [comment]
Hi, just wanted to check in , is there anything else needed from my side before this can move forward? Happy to make any additional changes.

**Comment by thc202** [comment]
There are still pending comments from the previous review.

File: addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils.java [hunk 6]
```diff
@@ -235,4 +285,11 @@ static Template getTemplateFromYamlFile(String templateName) throws Exception {
                                 "/reports/" + templateName + "/template.yaml")
                         .toFile());
     }
+
+    static DocumentBuilder newSecureDocumentBuilder() throws ParserConfigurationException {
```
Comment (thc202) [inline addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils.java]: I'm not sure about the need for this one, but if you really want use `XmlUtils.newXxeDisabledDocumentBuilderFactory()` instead.

Comment (miguel-baptista07) [reply addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils.java]: Used XmlUtils.newXxeDisabledDocumentBuilderFactory() as suggested. Please let me know if there's anything else needed.

**Comment by miguel-baptista07** [comment]
Hi, just flagging that the last review comment (XmlUtils) has been addressed in the latest push. Happy to make any further changes if needed.

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/pull/7290#discussion_r3110287437

File: addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils.java (hunk 6 above)
Comment (thc202) [reply addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportTestUtils.java]: fwiw this can be called directly no need for the indirection in the test utils.

**Comment by thc202** [comment]
It worth updating the commit message to match the latest changes (e.g. the old method is no longer being deprecated).

**Comment by miguel-baptista07** [comment]
All review comments from @thc202 and @kingthorin are now addressed:

isSystemic(Alert alert) removed entirely (it performed the wrong tag-based check and no template uses it)

Added Javadoc with @ since 0.45.0 to the new isSystemic(AlertNode, String, int) method

newSecureDocumentBuilder() indirection removed, XmlUtils called directly in the test

Duplicate getChildAt(0) extracted to firstChild variable
Given/When/Then structure added to both tests

CHANGELOG updated with suggested wording

Commit message updated to reflect the removal instead of deprecation

Happy to make any further changes if needed.

**Comment by thc202** [comment]
https://github.com/zaproxy/zap-extensions/pull/7290#discussion_r3110287437 is about the three lines (note 361 to 363), which are duplicating lines 202 to 204.

**Comment by miguel-baptista07** [comment]
> [#7290 (comment)](https://github.com/zaproxy/zap-extensions/pull/7290#discussion_r3110287437) is about the three lines (note 361 to 363), which are duplicating lines 202 to 204.

Refactored to eliminate the duplication, extracted a private findAlertNode(AlertNode, String, int) helper that encapsulates the shared lookup logic. Both getAlertInstancesForSite and isSystemic now delegate to it. Please let me know if anything else needs changing.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by miguel-baptista07** [comment]
Hi @kingthorin, just wanted to flag that @thc202 has approved the PR. Would you be able to take a look when you get a chance? Happy to make any further changes if needed.

**Comment by thc202** [comment]
Not necessary to ping us, we all receive notifications of comments and pushes.

**Review by kingthorin — APPROVED** [review]
